services:
  wordpress:
    image: wordpress:7.1.0-php8.3-apache
    networks:
      - rotborn_public
      - rotborn_private
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: rotborn
      WORDPRESS_DB_USER: rotborn
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}

  mariadb:
    image: mariadb:10.11
    networks:
      - rotborn_private
    env_file:
      - .env
    volumes:
      - /srv/rotborn/db:/var/lib/mysql
      - /srv/rotborn/config/mariadb/primary.cnf:/etc/mysql/conf.d/primary.cnf:ro

  mariadb-replica:
    image: mariadb:10.11
    networks:
      - rotborn_private
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /srv/rotborn/db-replica:/var/lib/mysql
      - /srv/rotborn/config/mariadb-replica/replica.cnf:/etc/mysql/conf.d/replica.cnf:ro

networks:
  rotborn_public:
    name: rotborn_public
    driver: bridge

  rotborn_private:
    name: rotborn_private
    driver: bridge
